# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abf62da6bbcd31a2d29dd38423fb3b07fa9bab463cad6e40c86bc518365676a446384953e7d98813df18aec17fc7afe5bbc844c13ba7374b1955bdde50b25f34

test:
  secret_key_base: e1ef7a5c11acc3a49756b50c19d2c042cda423a2c0e7d90e1358b121886c973296732101138c1ab6227192fcb0ff68cf4f739fab5817f08c0896d22692174984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
